### PR TITLE
Category filtering on click

### PR DESCRIPTION
**Pull request by Akamitori**
Implemented Category filtering

### CODE REVIEW

**Comment by zorbathut** [comment]
Pretty close!

I *think* this will be better off as a separate page, however. We're going to need to add category-specific stuff to it; we're better off building an actual CategoryPage thing, that contains a PostList and can also contain other things, rather than trying to roll a bunch of category-specific stuff into PostList itself.

This also means that PostList can continue to be dumb and just list the posts given to it, and it's the caller's responsibility to filter them as they see fit.

Also, the URL should end up at `/category/{categoryname}`.

**Comment by zorbathut** [comment]
Looks mostly good!

One bug: if you go to a category page, then click on a post, it doesn't actually bring you to the post, it just stays at the category page.

**Comment by Akamitori** [comment]
> Looks mostly good!
> 
> One bug: if you go to a category page, then click on a post, it doesn't actually bring you to the post, it just stays at the category page.

Fixed via [ce39f32b1fd0fa46cdc2b90e55fe068120a1bd57](https://github.com/themotte/vault/pull/112/commits/ce39f32b1fd0fa46cdc2b90e55fe068120a1bd57)

**Comment by zorbathut** [comment]
Looking better! One last issue: when you changed `Pages/Components/Post/Default.cshtml` it looks like you reformatted it from tabs to spaces. Can you either undo that, or submit the reformat as a separate pull request?

**Pull request closed without merging**
